# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import games_pb2 as games__pb2


class GameServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetGame = channel.unary_unary(
                '/game.GameService/GetGame',
                request_serializer=games__pb2.GetGameRequest.SerializeToString,
                response_deserializer=games__pb2.GetGameResponse.FromString,
                )
        self.SearchGames = channel.unary_unary(
                '/game.GameService/SearchGames',
                request_serializer=games__pb2.SearchGamesRequest.SerializeToString,
                response_deserializer=games__pb2.SearchGamesResponse.FromString,
                )
        self.AddGame = channel.unary_unary(
                '/game.GameService/AddGame',
                request_serializer=games__pb2.AddGameRequest.SerializeToString,
                response_deserializer=games__pb2.AddGameResponse.FromString,
                )


class GameServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetGame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchGames(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddGame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GameServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetGame': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGame,
                    request_deserializer=games__pb2.GetGameRequest.FromString,
                    response_serializer=games__pb2.GetGameResponse.SerializeToString,
            ),
            'SearchGames': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchGames,
                    request_deserializer=games__pb2.SearchGamesRequest.FromString,
                    response_serializer=games__pb2.SearchGamesResponse.SerializeToString,
            ),
            'AddGame': grpc.unary_unary_rpc_method_handler(
                    servicer.AddGame,
                    request_deserializer=games__pb2.AddGameRequest.FromString,
                    response_serializer=games__pb2.AddGameResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'game.GameService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GameService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/game.GameService/GetGame',
            games__pb2.GetGameRequest.SerializeToString,
            games__pb2.GetGameResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SearchGames(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/game.GameService/SearchGames',
            games__pb2.SearchGamesRequest.SerializeToString,
            games__pb2.SearchGamesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/game.GameService/AddGame',
            games__pb2.AddGameRequest.SerializeToString,
            games__pb2.AddGameResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
