# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: games.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bgames.proto\x12\x04game\"R\n\x04Game\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x0c\n\x04type\x18\x04 \x01(\t\x12\x0c\n\x04prix\x18\x05 \x01(\t\"!\n\x0eGetGameRequest\x12\x0f\n\x07game_id\x18\x01 \x01(\t\"+\n\x0fGetGameResponse\x12\x18\n\x04game\x18\x01 \x01(\x0b\x32\n.game.Game\"#\n\x12SearchGamesRequest\x12\r\n\x05query\x18\x01 \x01(\t\"0\n\x13SearchGamesResponse\x12\x19\n\x05games\x18\x01 \x03(\x0b\x32\n.game.Game\"P\n\x0e\x41\x64\x64GameRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\x0c\n\x04prix\x18\x04 \x01(\t\"+\n\x0f\x41\x64\x64GameResponse\x12\x18\n\x04game\x18\x01 \x01(\x0b\x32\n.game.Game2\xc1\x01\n\x0bGameService\x12\x36\n\x07GetGame\x12\x14.game.GetGameRequest\x1a\x15.game.GetGameResponse\x12\x42\n\x0bSearchGames\x12\x18.game.SearchGamesRequest\x1a\x19.game.SearchGamesResponse\x12\x36\n\x07\x41\x64\x64Game\x12\x14.game.AddGameRequest\x1a\x15.game.AddGameResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'games_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GAME']._serialized_start=21
  _globals['_GAME']._serialized_end=103
  _globals['_GETGAMEREQUEST']._serialized_start=105
  _globals['_GETGAMEREQUEST']._serialized_end=138
  _globals['_GETGAMERESPONSE']._serialized_start=140
  _globals['_GETGAMERESPONSE']._serialized_end=183
  _globals['_SEARCHGAMESREQUEST']._serialized_start=185
  _globals['_SEARCHGAMESREQUEST']._serialized_end=220
  _globals['_SEARCHGAMESRESPONSE']._serialized_start=222
  _globals['_SEARCHGAMESRESPONSE']._serialized_end=270
  _globals['_ADDGAMEREQUEST']._serialized_start=272
  _globals['_ADDGAMEREQUEST']._serialized_end=352
  _globals['_ADDGAMERESPONSE']._serialized_start=354
  _globals['_ADDGAMERESPONSE']._serialized_end=397
  _globals['_GAMESERVICE']._serialized_start=400
  _globals['_GAMESERVICE']._serialized_end=593
# @@protoc_insertion_point(module_scope)
