services:
  gateway-service:
    build:
      context: ./gateway
      args:
        - VERSION=${VERSION}
    image: achrafladhari/gateway:${VERSION}
    container_name: gateway
    ports:
      - '3000:3000'
    network_mode: host

  orders-service:
    build:
      context: ./orders
      args:
        - VERSION=${VERSION}
    image: achrafladhari/orders:${VERSION}
    container_name: orders
    ports:
      - '50053:50053'
    depends_on:
      - gateway-service
    network_mode: host

  users-service:
    build:
      context: ./users
      args:
        - VERSION=${VERSION}
    image: achrafladhari/users:${VERSION}
    container_name: users
    ports:
      - '50051:50051'
    depends_on:
      - gateway-service
    network_mode: host

  games-service:
    build:
      context: ./games
      args:
        - VERSION=${VERSION}
    image: achrafladhari/games:${VERSION}
    container_name: games
    ports:
      - '50052:50052'
    depends_on:
      - gateway-service
    network_mode: host

  swagger-service:
    build:
      context: ./swagger
      args:
        - VERSION=${VERSION}
    image: achrafladhari/swagger:${VERSION}
    container_name: swagger
    ports:
      - '4000:4000'
    depends_on:
      - gateway-service
    network_mode: host