services:
  gateway-service:
    build: "./gateway"
    ports:
      - '3000:3000'
    network_mode: host


  orders-service:
    build: "./orders"
    ports:
      - '50053:50053'
    depends_on:
      - gateway-service
    network_mode: host


  users-service:
    build: "./users"
    ports:
      - '50051:50051'
    depends_on:
      - gateway-service
    network_mode: host


  games-service:
    build: "./games"
    ports:
      - '50052:50052'
    depends_on:
      - gateway-service
    network_mode: host


  swagger-service:
    build: "./swagger"
    ports:
      - '4000:4000'
    depends_on:
      - gateway-service
    network_mode: host


