---
- name : "Build Automated App"
  hosts : localhost
  tasks:
  - name : Stop Containers and remove them
    command : docker compose down -v
    ignore_errors: yes
  
  - name : Remove gateway image
    command : docker rmi achrafladhari/gateway:$((BUILD_ID - 1)) --force
    ignore_errors: yes
    
  - name : Remove swagger image
    command : docker rmi achrafladhari/swagger:$((BUILD_ID - 1)) --force
    ignore_errors: yes
  
  - name : Remove orders service image
    command : docker rmi achrafladhari/orders:$((BUILD_ID - 1)) --force
    ignore_errors: yes

  - name : Remove games service image
    command : docker rmi achrafladhari/games:$((BUILD_ID - 1)) --force
    ignore_errors: yes

  - name : Remove users service image
    command : docker rmi achrafladhari/users:$((BUILD_ID - 1)) --force
    ignore_errors: yes